import { PUBLIC_DOC_SOURCES } from "@/content/publicDocs.generated";

export type DocEntry = {
  slug: string;
  title: string;
  category: string;
  content: string;
  blurb: string;
};

// Only allowlisted docs are bundled and served. The list lives in
// scripts/docs-allowlist.mjs and the imports are generated by
// `bun run docs:generate`; CI (docs-allowlist.yml) blocks drift.
// Internal material lives in internal-docs/ and is never bundled.
// This module is the single authorization boundary for public docs — both the
// DocsHub UI and the WebMCP tools read from it, so an agent can never reach
// anything a browser visitor cannot.
const INTERNAL_MARKER =
  /^\s*(?:>|\*\*|#{1,6})?\s*(?:classification:\s*)?(?:internal only|internal use only|confidential)/im;

export const publicDocs: DocEntry[] = PUBLIC_DOC_SOURCES
  .filter(([, content]) => !INTERNAL_MARKER.test(content.slice(0, 2000)))
  .map(([path, content]) => {
    const relativePath = path.replace(/\.md$/, "");
    const slug = relativePath
      .split("/")
      .map((segment) => segment.replace(/^\d+_?/, "").replace(/_/g, "-").toLowerCase())
      .join("/");

    const titleMatch = content.match(/^#\s+(.+)$/m);
    const bodyLines = content
      .split("\n")
      .map((line) => line.trim())
      .filter(
        (line) =>
          line &&
          !line.startsWith("#") &&
          !line.startsWith("![") &&
          !line.startsWith("```") &&
          !line.startsWith(">")
      );

    return {
      slug,
      title: titleMatch?.[1]?.trim() || relativePath.split("/").at(-1)?.replace(/_/g, " ") || "Document",
      category: relativePath.split("/")[0] || "general",
      content,
      blurb:
        bodyLines[0]?.replace(/[*_`]/g, "").slice(0, 160) ||
        "Implementation guide and reference documentation.",
    };
  })
  .sort((a, b) => a.title.localeCompare(b.title));

export const docBySlug = (slug: string): DocEntry | undefined =>
  publicDocs.find((d) => d.slug === slug);

/** Lightweight scored search over allowlisted docs (title > blurb > body). */
export const searchPublicDocs = (query: string, limit = 8) => {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean);
  if (!terms.length) return [];

  return publicDocs
    .map((doc) => {
      const title = doc.title.toLowerCase();
      const body = doc.content.toLowerCase();
      let score = 0;
      for (const term of terms) {
        if (title.includes(term)) score += 10;
        if (doc.slug.includes(term)) score += 6;
        if (doc.blurb.toLowerCase().includes(term)) score += 3;
        const occurrences = body.split(term).length - 1;
        score += Math.min(occurrences, 10);
      }
      return { doc, score };
    })
    .filter((row) => row.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
    .map(({ doc, score }) => ({
      slug: doc.slug,
      title: doc.title,
      category: doc.category,
      blurb: doc.blurb,
      url: `/docs/${doc.slug}`,
      score,
    }));
};
