-- Insert US Territories with SSURGO coverage
INSERT INTO counties (county_name, state_name, state_code, fips_code) VALUES

-- American Samoa (AS) - FIPS 60
('Eastern District', 'American Samoa', 'AS', '60010'),
('Manu''a District', 'American Samoa', 'AS', '60020'),
('Rose Island', 'American Samoa', 'AS', '60030'),
('Swains Island', 'American Samoa', 'AS', '60040'),
('Western District', 'American Samoa', 'AS', '60050'),

-- Guam (GU) - FIPS 66  
('Guam', 'Guam', 'GU', '66010'),

-- Northern Mariana Islands (MP) - FIPS 69
('Northern Islands', 'Northern Mariana Islands', 'MP', '60085'),
('Rota', 'Northern Mariana Islands', 'MP', '60100'),
('Saipan', 'Northern Mariana Islands', 'MP', '60110'),
('Tinian', 'Northern Mariana Islands', 'MP', '60120'),

-- Puerto Rico (PR) - FIPS 72 (Major municipalities with SSURGO data)
('Adjuntas', 'Puerto Rico', 'PR', '72001'),
('Aguada', 'Puerto Rico', 'PR', '72003'),
('Aguadilla', 'Puerto Rico', 'PR', '72005'),
('Aguas Buenas', 'Puerto Rico', 'PR', '72007'),
('Aibonito', 'Puerto Rico', 'PR', '72009'),
('Arecibo', 'Puerto Rico', 'PR', '72011'),
('Arroyo', 'Puerto Rico', 'PR', '72013'),
('Barceloneta', 'Puerto Rico', 'PR', '72015'),
('Barranquitas', 'Puerto Rico', 'PR', '72017'),
('Bayamón', 'Puerto Rico', 'PR', '72021'),
('Cabo Rojo', 'Puerto Rico', 'PR', '72023'),
('Caguas', 'Puerto Rico', 'PR', '72025'),
('Camuy', 'Puerto Rico', 'PR', '72027'),
('Canóvanas', 'Puerto Rico', 'PR', '72029'),
('Carolina', 'Puerto Rico', 'PR', '72031'),
('Cataño', 'Puerto Rico', 'PR', '72033'),
('Cayey', 'Puerto Rico', 'PR', '72035'),
('Cidra', 'Puerto Rico', 'PR', '72037'),
('Coamo', 'Puerto Rico', 'PR', '72039'),
('Comerío', 'Puerto Rico', 'PR', '72041'),
('Corozal', 'Puerto Rico', 'PR', '72043'),
('Culebra', 'Puerto Rico', 'PR', '72045'),
('Dorado', 'Puerto Rico', 'PR', '72047'),
('Fajardo', 'Puerto Rico', 'PR', '72049'),
('Florida', 'Puerto Rico', 'PR', '72051'),
('Guánica', 'Puerto Rico', 'PR', '72053'),
('Guayama', 'Puerto Rico', 'PR', '72055'),
('Guayanilla', 'Puerto Rico', 'PR', '72057'),
('Guaynabo', 'Puerto Rico', 'PR', '72059'),
('Gurabo', 'Puerto Rico', 'PR', '72061'),
('Hatillo', 'Puerto Rico', 'PR', '72063'),
('Hormigueros', 'Puerto Rico', 'PR', '72065'),
('Humacao', 'Puerto Rico', 'PR', '72067'),
('Isabela', 'Puerto Rico', 'PR', '72069'),
('Jayuya', 'Puerto Rico', 'PR', '72071'),
('Juana Díaz', 'Puerto Rico', 'PR', '72073'),
('Juncos', 'Puerto Rico', 'PR', '72075'),
('Lajas', 'Puerto Rico', 'PR', '72077'),
('Lares', 'Puerto Rico', 'PR', '72079'),
('Las Marías', 'Puerto Rico', 'PR', '72081'),
('Las Piedras', 'Puerto Rico', 'PR', '72083'),
('Loíza', 'Puerto Rico', 'PR', '72085'),
('Luquillo', 'Puerto Rico', 'PR', '72087'),
('Manatí', 'Puerto Rico', 'PR', '72091'),
('Maricao', 'Puerto Rico', 'PR', '72093'),
('Maunabo', 'Puerto Rico', 'PR', '72095'),
('Mayagüez', 'Puerto Rico', 'PR', '72097'),
('Moca', 'Puerto Rico', 'PR', '72099'),
('Morovis', 'Puerto Rico', 'PR', '72101'),
('Naguabo', 'Puerto Rico', 'PR', '72103'),
('Naranjito', 'Puerto Rico', 'PR', '72105'),
('Orocovis', 'Puerto Rico', 'PR', '72107'),
('Patillas', 'Puerto Rico', 'PR', '72109'),
('Peñuelas', 'Puerto Rico', 'PR', '72111'),
('Ponce', 'Puerto Rico', 'PR', '72113'),
('Quebradillas', 'Puerto Rico', 'PR', '72115'),
('Rincón', 'Puerto Rico', 'PR', '72117'),
('Río Grande', 'Puerto Rico', 'PR', '72119'),
('Sabana Grande', 'Puerto Rico', 'PR', '72121'),
('Salinas', 'Puerto Rico', 'PR', '72123'),
('San Germán', 'Puerto Rico', 'PR', '72125'),
('San Juan', 'Puerto Rico', 'PR', '72127'),
('San Lorenzo', 'Puerto Rico', 'PR', '72129'),
('San Sebastián', 'Puerto Rico', 'PR', '72131'),
('Santa Isabel', 'Puerto Rico', 'PR', '72133'),
('Toa Alta', 'Puerto Rico', 'PR', '72135'),
('Toa Baja', 'Puerto Rico', 'PR', '72137'),
('Trujillo Alto', 'Puerto Rico', 'PR', '72139'),
('Utuado', 'Puerto Rico', 'PR', '72141'),
('Vega Alta', 'Puerto Rico', 'PR', '72143'),
('Vega Baja', 'Puerto Rico', 'PR', '72145'),
('Vieques', 'Puerto Rico', 'PR', '72147'),
('Villalba', 'Puerto Rico', 'PR', '72149'),
('Yabucoa', 'Puerto Rico', 'PR', '72151'),
('Yauco', 'Puerto Rico', 'PR', '72153'),

-- US Virgin Islands (VI) - FIPS 78
('St. Croix', 'US Virgin Islands', 'VI', '78010'),
('St. John', 'US Virgin Islands', 'VI', '78020'),
('St. Thomas', 'US Virgin Islands', 'VI', '78030'),

-- Pacific Territories with SSURGO coverage
-- Marshall Islands (MH) - Compact states with SSURGO data
('Majuro Atoll', 'Marshall Islands', 'MH', '68010'),
('Kwajalein Atoll', 'Marshall Islands', 'MH', '68020'),

-- Federated States of Micronesia (FM) - Compact states with SSURGO data  
('Chuuk', 'Federated States of Micronesia', 'FM', '64010'),
('Kosrae', 'Federated States of Micronesia', 'FM', '64020'),
('Pohnpei', 'Federated States of Micronesia', 'FM', '64030'),
('Yap', 'Federated States of Micronesia', 'FM', '64040'),

-- Republic of Palau (PW) - Compact state with SSURGO data
('Airai', 'Republic of Palau', 'PW', '70002'),
('Angaur', 'Republic of Palau', 'PW', '70004'),
('Hatohobei', 'Republic of Palau', 'PW', '70010'),
('Kayangel', 'Republic of Palau', 'PW', '70050'),
('Koror', 'Republic of Palau', 'PW', '70100'),
('Melekeok', 'Republic of Palau', 'PW', '70150'),
('Ngaraard', 'Republic of Palau', 'PW', '70212'),
('Ngarchelong', 'Republic of Palau', 'PW', '70214'),
('Ngardmau', 'Republic of Palau', 'PW', '70218'),
('Ngatpang', 'Republic of Palau', 'PW', '70222'),
('Ngchesar', 'Republic of Palau', 'PW', '70224'),
('Ngeremlengui', 'Republic of Palau', 'PW', '70226'),
('Ngiwal', 'Republic of Palau', 'PW', '70227'),
('Peleliu', 'Republic of Palau', 'PW', '70350'),
('Sonsorol', 'Republic of Palau', 'PW', '70370')

ON CONFLICT (fips_code) DO NOTHING;